version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  cmd:
    build:
      context: ./cmd
    container_name: cmd
    restart: always
    environment:
      - DB_URL=postgresql://root:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
  